src/main/clojure/com/github/clojure_repl/intellij/action/load_file.clj, src/main/clojure/com/github/clojure_repl/intellij/configuration/repl_client.clj, src/main/clojure/com/github/clojure_repl/intellij/db.clj, src/main/clojure/com/github/clojure_repl/intellij/nrepl.clj, src/main/clojure/com/github/clojure_repl/intellij/ui/repl.clj
Fixes #10
Fixes #9 
Maybe fix #12 but needs more user feedback
- fix the handle process reset
- create the db namespace for state used across whole plugin
- create a nrepl ns for nrepl interactions
- print clojure, java, nrepl and plugin versions on process startup
=> Fix repl process state

src/main/clojure/com/github/clojure_repl/intellij/configuration/repl_client.clj, src/main/clojure/com/github/clojure_repl/intellij/db.clj
Closes #16 
Still need to understand what we should do when there is an operation not supported. 
This PR did not cover this, because I think that those basic operations should always be supported or we can not even communicate with the nrepl server.
=> store versions and operations in db

src/main/clojure/com/github/clojure_repl/intellij/configuration/repl_client.clj, src/main/clojure/com/github/clojure_repl/intellij/ui/repl.clj
=> Setup settings when starting the process

build.gradle.kts, deps.edn, src/main/clojure/com/github/clojure_repl/intellij/action/eval_last_sexp.clj, src/main/clojure/com/github/clojure_repl/intellij/editor.clj, src/main/clojure/com/github/clojure_repl/intellij/nrepl.clj, src/main/clojure/com/github/clojure_repl/intellij/parser.clj, src/main/resources/META-INF/plugin.xml
=> Add support for eval sexp

src/main/clojure/com/github/clojure_repl/intellij/action/eval_last_sexp.clj, src/main/clojure/com/github/clojure_repl/intellij/action/switch_ns.clj, src/main/clojure/com/github/clojure_repl/intellij/configuration/repl_client.clj, src/main/clojure/com/github/clojure_repl/intellij/db.clj, src/main/clojure/com/github/clojure_repl/intellij/nrepl.clj, src/main/clojure/com/github/clojure_repl/intellij/parser.clj, src/main/resources/META-INF/plugin.xml
=> Add switch ns action

src/main/clojure/com/github/clojure_repl/intellij/action/eval_last_sexp.clj, src/main/clojure/com/github/clojure_repl/intellij/action/load_file.clj, src/main/clojure/com/github/clojure_repl/intellij/nrepl.clj, src/main/clojure/com/github/clojure_repl/intellij/ui/repl.clj
=> Fix eval output and load-file output when error

CHANGELOG.md, build.gradle.kts, deps.edn, src/main/clojure/com/github/clojure_repl/intellij/configuration/factory/local.clj, src/main/clojure/com/github/clojure_repl/intellij/repl_command.clj, src/test/clojure/com/github/clojure_repl/intellij/repl_command_test.clj
Fixes #27
- Use for local server cider-nrepl 
- create tests for the generated command
=> Add cider-nrepl middleware

CHANGELOG.md, src/main/clojure/com/github/clojure_repl/intellij/configuration/factory/local.clj, src/main/clojure/com/github/clojure_repl/intellij/project.clj
=> regression: Fix run configuration when project-type is not configured

.github/workflows/publish_plugin.yaml
@afucher can you setup the JETBRAINS_TOKEN secret on this repo?
=> Add publish plugin CI on new tag

CHANGELOG.md, src/main/clojure/com/github/clojure_repl/intellij/action/eval.clj
=> Show error message for namespace-not-found

src/main/clojure/com/github/clojure_repl/intellij/ui/inlay_hint.clj
=> Fix language inexistent when evaluating

src/main/clojure/com/github/clojure_repl/intellij/extension/color_settings_page.clj, src/main/clojure/com/github/clojure_repl/intellij/tool_window/repl_test.clj, src/main/clojure/com/github/clojure_repl/intellij/ui/color.clj, src/main/clojure/com/github/clojure_repl/intellij/ui/inlay_hint.clj, src/main/clojure/com/github/clojure_repl/intellij/ui/repl.clj, src/main/resources/META-INF/plugin.xml
- Fix esc no working for inline inlay hint
- Add color settings page for customization of some tokens (it's still basic, needs more polish in next PRs
)
=> Colors settings

build.gradle.kts
this includes the proxy+ hook improving dev xp
=> Bump clj4intellij to 0.6.3

src/main/clojure/com/github/clojure_repl/intellij/configuration/settings_editor/local.clj, src/main/clojure/com/github/clojure_repl/intellij/configuration/settings_editor/remote.clj
If user doesn't name the RunConfiguration, when saving it will update to a better default name
=> Avoid unnamed runconfigurations

CHANGELOG.md, src/main/clojure/com/github/clojure_repl/intellij/action/eval.clj
=> fix error when running eval defun at cursos action

CHANGELOG.md, src/main/clojure/com/github/clojure_repl/intellij/ui/repl.clj
=> Block backspace the repl input

CHANGELOG.md, src/main/clojure/com/github/clojure_repl/intellij/action/eval.clj, src/main/clojure/com/github/clojure_repl/intellij/configuration/factory/base.clj, src/main/clojure/com/github/clojure_repl/intellij/tests.clj, src/main/clojure/com/github/clojure_repl/intellij/ui/repl.clj
when switching ns with `alt + shift + e` `alt + shift + n`, the repl should update the new ns
=> update repl ns after switching ns

CHANGELOG.md, src/main/clojure/com/github/clojure_repl/intellij/extension/color_settings_page.clj, src/main/clojure/com/github/clojure_repl/intellij/ui/color.clj
Fix this exception on master in a permanent way:
The exception happens when opening the intellij settings
```java
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'displayName' of com/intellij/openapi/options/colors/AttributesDescriptor.<init> must not be null
at com.intellij.openapi.options.colors.AttributesDescriptor.$$$reportNull$$$0(AttributesDescriptor.java)
at com.intellij.openapi.options.colors.AttributesDescriptor.<init>(AttributesDescriptor.java)
at com.github.clojure_repl.intellij.extension.color_settings_page$_getAttributeDescriptors$fn__17053.invoke(color_settings_page.clj:27)
at clojure.core$mapv$fn__8535.invoke(core.clj:6979)
at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75 …
```
=> Fix missing text attrs on color settings page

CHANGELOG.md, src/main/clojure/com/github/clojure_repl/intellij/configuration/factory/local.clj, src/main/clojure/com/github/clojure_repl/intellij/configuration/settings_editor/local.clj, src/main/clojure/com/github/clojure_repl/intellij/repl_command.clj, src/main/clojure/com/github/clojure_repl/intellij/ui/components.clj, src/main/kotlin/run-configuration-options.kt
Fixes #124 
- Support JVM args on local configuration
- Refactor local configuration extracing multi-field to a component.
=> Support JVM args on local repl configuration

CHANGELOG.md, src/main/clojure/com/github/clojure_repl/intellij/action/eval.clj
=> Fix special forms evaluations

CHANGELOG.md, src/main/clojure/com/github/clojure_repl/intellij/extension/register_actions_startup.clj, src/main/clojure/com/github/clojure_repl/intellij/nrepl.clj
=> Disable clear REPL action when it is not ready

CHANGELOG.md, src/main/clojure/com/github/clojure_repl/intellij/repl_command.clj, src/test/clojure/com/github/clojure_repl/intellij/repl_command_test.clj
=> Bump nrepl + cider-nrepl
