src/main/clojure/com/github/clojure_repl/intellij/action/load_file.clj
src/main/clojure/com/github/clojure_repl/intellij/configuration/repl_client.clj
src/main/clojure/com/github/clojure_repl/intellij/db.clj
src/main/clojure/com/github/clojure_repl/intellij/nrepl.clj
src/main/clojure/com/github/clojure_repl/intellij/ui/repl.clj
src/main/kotlin/run-configuration-options.kt

When using `Load File REPL` action, we do not have any information about the file. This PR aims to show to the user in the console the file that is being loaded.
Added project field to configuration, uses it to related actions and repl.
It does not cover error cases. For this I created another issue: #22

show loading file path on console

---

src/main/clojure/com/github/clojure_repl/intellij/action/eval_last_sexp.clj

IntelliJ editor consider the first line as 0, but rewrite-clj expect the first line to be 1.
Leave the editor ns without inc, because I think that it should be just a pure proxy for the IntelliJ editors API.

fix difference between line start number in editor and rewrite-clj

---

CHANGELOG.md
src/main/clojure/com/github/clojure_repl/intellij/action/eval_last_sexp.clj
src/main/clojure/com/github/clojure_repl/intellij/action/load_file.clj
src/main/clojure/com/github/clojure_repl/intellij/action/switch_ns.clj
src/main/clojure/com/github/clojure_repl/intellij/configuration/repl.clj
src/main/clojure/com/github/clojure_repl/intellij/configuration/repl_client.clj
src/main/clojure/com/github/clojure_repl/intellij/nrepl.clj
src/main/clojure/com/github/clojure_repl/intellij/ui/repl.clj
src/main/clojure/com/github/clojure_repl/intellij/ui/repl_hint.clj
src/main/kotlin/run-configuration-options.kt
src/main/resources/META-INF/plugin.xml

Fixes #34
- Fix REPL output from #34
- Clear REPL state on disconnection, to avoid allow eval things even with repl disconnected
- Fix an exception that happens after some time using the plugin
- Refactor: prepare ConfigurationType to support multiple ConfigurationFactories in the future

Fix duplicated output to repl + other improvements

---

README.md

In looking to get started with `clojure-repl-intellij`, the first place I checked was the `README`. Currently, the `README` does not have Getting Started instructions.
Add a modified version of the Getting Started steps from the [IntelliJ Plugin Marketplace page](https://plugins.jetbrains.com/plugin/23073-clojure-repl) to the `README`.

Add Getting Started steps to README

---

src/main/clojure/com/github/clojure_repl/intellij/action/eval_last_sexp.clj
src/main/clojure/com/github/clojure_repl/intellij/action/load_file.clj
src/main/clojure/com/github/clojure_repl/intellij/configuration/factory/base.clj
src/main/clojure/com/github/clojure_repl/intellij/configuration/factory/local.clj
src/main/clojure/com/github/clojure_repl/intellij/configuration/factory/remote.clj
src/main/clojure/com/github/clojure_repl/intellij/db.clj
src/main/clojure/com/github/clojure_repl/intellij/tests.clj
src/main/clojure/com/github/clojure_repl/intellij/ui/repl.clj

This moves all other states to db since now we have it segregated by project making easier to manage and less error prone

Move other atoms to db

---

src/main/clojure/com/github/clojure_repl/intellij/action/eval_last_sexp.clj
src/main/clojure/com/github/clojure_repl/intellij/action/load_file.clj
src/main/clojure/com/github/clojure_repl/intellij/action/switch_ns.clj
src/main/clojure/com/github/clojure_repl/intellij/configuration/factory/base.clj
src/main/clojure/com/github/clojure_repl/intellij/configuration/factory/local.clj
src/main/clojure/com/github/clojure_repl/intellij/db.clj
src/main/clojure/com/github/clojure_repl/intellij/nrepl.clj
src/main/clojure/com/github/clojure_repl/intellij/ui/repl.clj

Fixes #22 
This combine the multiple repsonses into one using a nrepl function to do that, now when running a test we can see multiple output:

Fix multiple responses from nrepl message

---

CHANGELOG.md
build.gradle.kts
deps.edn

We were registering the actions everytime a new project is opened, this fix these exceptions:
```
java.lang.Throwable: ID 'ClojureREPL.RunCursorTest' is already taken by action 'Run test at cursor (Run test at cursor)' (class com.intellij.openapi.actionSystem.impl.ChameleonAction) . Action 'Run test at cursor (Run test at cursor)' (class com.github.ericdallo.clj4intellij.action.proxy_plus2918) cannot use the same ID null
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionIdCollision(ActionManagerImpl.kt:964)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.kt:906)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.kt:973 …
```

Fix noisy exceptions introduced on 1.0.1 when opening multiple projects.

---

CHANGELOG.md
src/main/clojure/com/github/clojure_repl/intellij/action/eval.clj
src/main/clojure/com/github/clojure_repl/intellij/extension/register_actions_startup.clj
src/main/clojure/com/github/clojure_repl/intellij/nrepl.clj

- When a namespace has a eval error we were not showing the error + saying the file was loaded which is wrong
- not require to save the file to load it, use current changes in buffer

regression: Fix load file to handle errors

---

build.gradle.kts
deps.edn
src/main/clojure/com/github/clojure_repl/intellij/configuration/factory/base.clj
src/main/clojure/com/github/clojure_repl/intellij/configuration/factory/local.clj
src/main/clojure/com/github/clojure_repl/intellij/nrepl.clj

- Fixes #65
- Fix a exception that happens after some seconds of repl running:
```
If it's a long-running mostly idle daemon process, consider overriding OSProcessHandler#readerOptions with 'BaseOutputReader.Options.forMostlySilentProcess()' to reduce CPU usage.
Command line: lein update-in :dependencies conj "[nrepl/nrepl \"1.0.0\"]" -- update-in :plugins conj "[cider/cider-nrepl \"0.45.0\"]" -- repl :headless :host localhost
java.lang.Throwable: Process creation:
at com.intellij.execution.process.BaseOSProcessHandler.<init>
```
This PR refactors how we communicate with NREPL, the major problem is that nrepl is a server so it can send messages at any time through the socket, and we were ignoring those messages, only caring by the ones we sent sync.
Code snippets to test:
```clojure …
```

Refactor nrepl communication to handle Transport manually

---

CHANGELOG.md
README.md
doc/shortcuts.md
src/main/clojure/com/github/clojure_repl/intellij/action/eval.clj
src/main/clojure/com/github/clojure_repl/intellij/extension/register_actions_startup.clj

This adds a new action to eval the current top level form (defun) at cursor, used a lot in cider and calva

Add new action to eval defun at cursor

---

CHANGELOG.md
src/main/clojure/com/github/clojure_repl/intellij/configuration/settings_editor/remote.clj

We were missing checking for the mode when loading a previously saved configuration

Fix remote run configuration wrong state after open

---

CHANGELOG.md
README.md
src/main/clojure/com/github/clojure_repl/intellij/configuration/factory/base.clj
src/main/clojure/com/github/clojure_repl/intellij/db.clj
src/main/clojure/com/github/clojure_repl/intellij/ui/repl.clj

Add support to entry history navigation. 
Uses `ctrl+PG_UP` and `ctrl+PG_DOWN` to navigate.
https://github.com/afucher/clojure-repl-intellij/assets/3756185/92debcd5-f317-4c60-8bdb-290af4540c0f
Closes #66

Add support to entry history navigation

---

CHANGELOG.md
README.md
src/main/clojure/com/github/clojure_repl/intellij/ui/color.clj
src/main/clojure/com/github/clojure_repl/intellij/ui/repl.clj

Picture of the REPL now inheriting the right color

Sets the color of the repl to IntelliJ's background

---

CHANGELOG.md
src/main/clojure/com/github/clojure_repl/intellij/action/eval.clj
src/main/clojure/com/github/clojure_repl/intellij/parser.clj
src/main/clojure/com/github/clojure_repl/intellij/tests.clj

Problem:
* It is considering the metadata as the namespace name, so when trying to change the namespace in RELP, an error occurs.
**Without metadata:**
**With metadata:**
**After fix:**

Fix - in RELP actions shouldn't consider namespace metadata

---

README.md

It took me a minute to find the link. I believe that adding the link here will remove a tiny bit of friction for some users

Add a link to the plugin to the Getting started section

---

CHANGELOG.md
src/main/clojure/com/github/clojure_repl/intellij/db.clj
src/main/clojure/com/github/clojure_repl/intellij/tests.clj
src/main/clojure/com/github/clojure_repl/intellij/tool_window/repl_test.clj

Fixes #74 
Segregate test-fns by project so each project has its own tool-window avoiding issues.

segregate test fns by project

---

.gitignore
CHANGELOG.md
src/main/clojure/com/github/clojure_repl/intellij/configuration/factory/remote.clj
src/main/clojure/com/github/clojure_repl/intellij/configuration/settings_editor/remote.clj

The plugin was handling wrongly the `mode` for remote configurations, causing the UI to be different from what was really running.
Discovered this trying to reproduce #95

fix: convert mode to keyword to be handled correctly

---

src/main/clojure/com/github/clojure_repl/intellij/tool_window/repl_test.clj
src/main/clojure/com/github/clojure_repl/intellij/ui/color.clj

it's not a good idea run IntelliJ code during `def` blocks, as they are evaluated during compile time and intellij classers may depend on intellij runtime.
This may cause build-plugin to fail depending on SO/intellij version:
```java
java.lang.Throwable: Must be precomputed                                                                                                                        
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)                                                                                        
at com.intellij.ui.scale.JBUIScale.computeSystemScaleFactor(JBUIScale.kt:208)                                                                           
at com.intellij.ui.scale.JBUIScale$systemScaleFactor$1.invoke(JBUIScale.kt:83) …
```

Fix corner case that may cause build-plugin to fail

---

src/main/clojure/com/github/clojure_repl/intellij/db.clj

This fixe the `empty-project` that was not being assoced properly when db was initializing

Fix :project inside db

---

CHANGELOG.md
src/main/clojure/com/github/clojure_repl/intellij/action/eval.clj
src/main/clojure/com/github/clojure_repl/intellij/configuration/factory/base.clj
src/main/clojure/com/github/clojure_repl/intellij/configuration/factory/local.clj
src/main/clojure/com/github/clojure_repl/intellij/db.clj
src/main/clojure/com/github/clojure_repl/intellij/nrepl.clj
src/main/clojure/com/github/clojure_repl/intellij/tests.clj
src/main/clojure/com/github/clojure_repl/intellij/ui/repl.clj
src/test/clojure/com/github/clojure_repl/intellij/ui/repl_test.clj

Fixes #92 
- All eval actions now send to REPL
- Changed repl window eval to not append a `;;` since now we have syntax coloring, color the result may be good
- Fix repl input when evaluated the same input of last eval.
- Fix history navigation via shortcut not working after 2.0.0.

Add history eval to repl

---

CHANGELOG.md
src/main/clojure/com/github/clojure_repl/intellij/configuration/factory/base.clj
src/main/clojure/com/github/clojure_repl/intellij/nrepl.clj

Fix how the plugin handle the messages from the connected REPL. Every `:out` message now will be sent to the REPL Console view.
https://github.com/user-attachments/assets/631c97e3-3bf9-40df-945a-a8b8cb133213
https://github.com/user-attachments/assets/529657b1-2e7a-408c-a7a6-699e3fe31b44
Fixes #153

fix: out messages of REPL where not being sent to REPL window

---

CHANGELOG.md
src/main/clojure/com/github/clojure_repl/intellij/parser.clj
src/test/clojure/com/github/clojure_repl/intellij/parser_test.clj

Fix parser to handle namespaced def forms like s/deftest
**Problem**
The `find-var-at-pos` function failed to identify variable names in namespaced def forms like `(s/deftest a 1)` because it was checking if the form string started with "def", but namespaced forms start with the namespace prefix.  
**Solution**
Updated `var-name-loc-from-op` to extract the symbol name by splitting on "/" and checking if the symbol name (not the full form) starts with "def".
```clojure
;; Before: Failed
(-> (find-var-at-pos (z/of-string "(s/deftest a 1)") 1 4) z/string)
;; => nil
;; After: Works correctly
(-> (find-var-at-pos (z/of-string "(s/deftest a 1)") 1 4) z/string)
;; => "a"
```

fix parser to check only symbol

---

CHANGELOG.md
src/main/clojure/com/github/clojure_repl/intellij/action/custom_code_actions.clj

The issue with Custom Code Actions and new versions of IntelliJ is that they changed the signature of the `DefaultActionGroup/.getChildren`, so we need to handle both versions.
Using type hint is not working in this case, probably is because when it compiles it uses the min version of IntelliJ library and this version not has the new method signature.
It puts type hint as `AnActionEvent`, what is wrong:
```java
public static Object invokeStatic(Object group) {
Object var10000 = ((IFn)const__0.getRawRoot()).invoke("252.13776.59");
AnAction[] var1;
if (var10000 != null) {
if (var10000 != Boolean.FALSE) {
var10000 = group;
group = null;
// Wrong cast
var1 = ((DefaultActionGroup)var10000).getChildren((AnActionEvent)ActionManager.getInstance());
return var1;
}
}
var10000 = group;
group = null; …
```

fix: Custom Code Actions
